package pTitulo2;
// Generated May 4, 2016 2:55:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Neoproyecto generated by hbm2java
 */
@Entity
@Table(name="neoproyecto"
    ,schema="public"
)
public class Neoproyecto  implements java.io.Serializable {


     private int id;
     private Profesor profesor;
     private String nombre;
     private String areaInteres;
     private Integer cupo;
     private Date fechaPublicacion;
     private Integer tiempoAprox;
     private Integer duracionAprox;
     private String descripcion;

    public Neoproyecto() {
    }

	
    public Neoproyecto(int id) {
        this.id = id;
    }
    public Neoproyecto(int id, Profesor profesor, String nombre, String areaInteres, Integer cupo, Date fechaPublicacion, Integer tiempoAprox, Integer duracionAprox, String descripcion) {
       this.id = id;
       this.profesor = profesor;
       this.nombre = nombre;
       this.areaInteres = areaInteres;
       this.cupo = cupo;
       this.fechaPublicacion = fechaPublicacion;
       this.tiempoAprox = tiempoAprox;
       this.duracionAprox = duracionAprox;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_profeso")
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="area_interes")
    public String getAreaInteres() {
        return this.areaInteres;
    }
    
    public void setAreaInteres(String areaInteres) {
        this.areaInteres = areaInteres;
    }

    
    @Column(name="cupo")
    public Integer getCupo() {
        return this.cupo;
    }
    
    public void setCupo(Integer cupo) {
        this.cupo = cupo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_publicacion", length=13)
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }

    
    @Column(name="tiempo_aprox")
    public Integer getTiempoAprox() {
        return this.tiempoAprox;
    }
    
    public void setTiempoAprox(Integer tiempoAprox) {
        this.tiempoAprox = tiempoAprox;
    }

    
    @Column(name="duracion_aprox")
    public Integer getDuracionAprox() {
        return this.duracionAprox;
    }
    
    public void setDuracionAprox(Integer duracionAprox) {
        this.duracionAprox = duracionAprox;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


