package pTitulo;
// Generated Apr 26, 2016 2:53:12 PM by Hibernate Tools 4.3.1


import dao.ProfesorDao;
import java.util.HashSet;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name="profesor"
    ,schema="public"
)
@ManagedBean
public class Profesor  implements java.io.Serializable {


     private int noCuenta;
     private String nombre;
     private String apellidom;
     private String apellidop;
     private String email;
     private String password;
     private String GEstudios;
     private String areaInv;
     private Set neoproyectos = new HashSet(0);
     private Set estudiantes = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(int noCuenta) {
        this.noCuenta = noCuenta;
    }
    public Profesor(int noCuenta, String nombre, String apellidom, String apellidop, String email, String password, String GEstudios, String areaInv, Set neoproyectos, Set estudiantes) {
       this.noCuenta = noCuenta;
       this.nombre = nombre;
       this.apellidom = apellidom;
       this.apellidop = apellidop;
       this.email = email;
       this.password = password;
       this.GEstudios = GEstudios;
       this.areaInv = areaInv;
       this.neoproyectos = neoproyectos;
       this.estudiantes = estudiantes;
    }
   
     @Id 

    
    @Column(name="no_cuenta", unique=true, nullable=false)
    public int getNoCuenta() {
        return this.noCuenta;
    }
    
    public void setNoCuenta(int noCuenta) {
        this.noCuenta = noCuenta;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidom")
    public String getApellidom() {
        return this.apellidom;
    }
    
    public void setApellidom(String apellidom) {
        this.apellidom = apellidom;
    }

    
    @Column(name="apellidop")
    public String getApellidop() {
        return this.apellidop;
    }
    
    public void setApellidop(String apellidop) {
        this.apellidop = apellidop;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="g_estudios")
    public String getGEstudios() {
        return this.GEstudios;
    }
    
    public void setGEstudios(String GEstudios) {
        this.GEstudios = GEstudios;
    }

    
    @Column(name="area_inv")
    public String getAreaInv() {
        return this.areaInv;
    }
    
    public void setAreaInv(String areaInv) {
        this.areaInv = areaInv;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profesor")
    public Set getNeoproyectos() {
        return this.neoproyectos;
    }
    
    public void setNeoproyectos(Set neoproyectos) {
        this.neoproyectos = neoproyectos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profesor")
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }

    public String guardarProfesor(){
        System.out.println(this.noCuenta);
        ProfesorDao sdao = new ProfesorDao();
        sdao.agregarProfesor(this);
        return "PublicarProyectoIH";
    }


}


