package titulo;
// Generated Apr 10, 2016 11:22:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private BigDecimal noCuenta;
     private Admin admin;
     private Profesor profesor;
     private Proyecto proyecto;
     private String nombre;
     private String apellidop;
     private String apellidom;
     private String email;
     private String password;
     private BigDecimal porcentajeCredi;
     private String carrera;
     private String fechaRegistro;
     private Date fechaAsigProyecto;
     private Set<SolicitarProyecto> solicitarProyectos = new HashSet<SolicitarProyecto>(0);

    public Estudiante() {
    }

	
    public Estudiante(BigDecimal noCuenta) {
        this.noCuenta = noCuenta;
    }
    public Estudiante(BigDecimal noCuenta, Admin admin, Profesor profesor, Proyecto proyecto, String nombre, String apellidop, String apellidom, String email, String password, BigDecimal porcentajeCredi, String carrera, String fechaRegistro, Date fechaAsigProyecto, Set<SolicitarProyecto> solicitarProyectos) {
       this.noCuenta = noCuenta;
       this.admin = admin;
       this.profesor = profesor;
       this.proyecto = proyecto;
       this.nombre = nombre;
       this.apellidop = apellidop;
       this.apellidom = apellidom;
       this.email = email;
       this.password = password;
       this.porcentajeCredi = porcentajeCredi;
       this.carrera = carrera;
       this.fechaRegistro = fechaRegistro;
       this.fechaAsigProyecto = fechaAsigProyecto;
       this.solicitarProyectos = solicitarProyectos;
    }
   
    public BigDecimal getNoCuenta() {
        return this.noCuenta;
    }
    
    public void setNoCuenta(BigDecimal noCuenta) {
        this.noCuenta = noCuenta;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidop() {
        return this.apellidop;
    }
    
    public void setApellidop(String apellidop) {
        this.apellidop = apellidop;
    }
    public String getApellidom() {
        return this.apellidom;
    }
    
    public void setApellidom(String apellidom) {
        this.apellidom = apellidom;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public BigDecimal getPorcentajeCredi() {
        return this.porcentajeCredi;
    }
    
    public void setPorcentajeCredi(BigDecimal porcentajeCredi) {
        this.porcentajeCredi = porcentajeCredi;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public String getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(String fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaAsigProyecto() {
        return this.fechaAsigProyecto;
    }
    
    public void setFechaAsigProyecto(Date fechaAsigProyecto) {
        this.fechaAsigProyecto = fechaAsigProyecto;
    }
    public Set<SolicitarProyecto> getSolicitarProyectos() {
        return this.solicitarProyectos;
    }
    
    public void setSolicitarProyectos(Set<SolicitarProyecto> solicitarProyectos) {
        this.solicitarProyectos = solicitarProyectos;
    }




}


