package titulo;
// Generated Apr 10, 2016 11:22:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private BigDecimal id;
     private Profesor profesor;
     private String nombre;
     private String areaInteres;
     private BigDecimal cupo;
     private Date fechaPublicacion;
     private BigDecimal tiempoAprox;
     private BigDecimal duracionAprox;
     private Set<SolicitarProyecto> solicitarProyectos = new HashSet<SolicitarProyecto>(0);
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Proyecto() {
    }

	
    public Proyecto(BigDecimal id) {
        this.id = id;
    }
    public Proyecto(BigDecimal id, Profesor profesor, String nombre, String areaInteres, BigDecimal cupo, Date fechaPublicacion, BigDecimal tiempoAprox, BigDecimal duracionAprox, Set<SolicitarProyecto> solicitarProyectos, Set<Estudiante> estudiantes) {
       this.id = id;
       this.profesor = profesor;
       this.nombre = nombre;
       this.areaInteres = areaInteres;
       this.cupo = cupo;
       this.fechaPublicacion = fechaPublicacion;
       this.tiempoAprox = tiempoAprox;
       this.duracionAprox = duracionAprox;
       this.solicitarProyectos = solicitarProyectos;
       this.estudiantes = estudiantes;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAreaInteres() {
        return this.areaInteres;
    }
    
    public void setAreaInteres(String areaInteres) {
        this.areaInteres = areaInteres;
    }
    public BigDecimal getCupo() {
        return this.cupo;
    }
    
    public void setCupo(BigDecimal cupo) {
        this.cupo = cupo;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public BigDecimal getTiempoAprox() {
        return this.tiempoAprox;
    }
    
    public void setTiempoAprox(BigDecimal tiempoAprox) {
        this.tiempoAprox = tiempoAprox;
    }
    public BigDecimal getDuracionAprox() {
        return this.duracionAprox;
    }
    
    public void setDuracionAprox(BigDecimal duracionAprox) {
        this.duracionAprox = duracionAprox;
    }
    public Set<SolicitarProyecto> getSolicitarProyectos() {
        return this.solicitarProyectos;
    }
    
    public void setSolicitarProyectos(Set<SolicitarProyecto> solicitarProyectos) {
        this.solicitarProyectos = solicitarProyectos;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


