package titulo;
// Generated Apr 10, 2016 11:22:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SolicitarProyectoId generated by hbm2java
 */
public class SolicitarProyectoId  implements java.io.Serializable {


     private BigDecimal idEstudiante;
     private BigDecimal idProyecto;

    public SolicitarProyectoId() {
    }

    public SolicitarProyectoId(BigDecimal idEstudiante, BigDecimal idProyecto) {
       this.idEstudiante = idEstudiante;
       this.idProyecto = idProyecto;
    }
   
    public BigDecimal getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(BigDecimal idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
    public BigDecimal getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(BigDecimal idProyecto) {
        this.idProyecto = idProyecto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SolicitarProyectoId) ) return false;
		 SolicitarProyectoId castOther = ( SolicitarProyectoId ) other; 
         
		 return ( (this.getIdEstudiante()==castOther.getIdEstudiante()) || ( this.getIdEstudiante()!=null && castOther.getIdEstudiante()!=null && this.getIdEstudiante().equals(castOther.getIdEstudiante()) ) )
 && ( (this.getIdProyecto()==castOther.getIdProyecto()) || ( this.getIdProyecto()!=null && castOther.getIdProyecto()!=null && this.getIdProyecto().equals(castOther.getIdProyecto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEstudiante() == null ? 0 : this.getIdEstudiante().hashCode() );
         result = 37 * result + ( getIdProyecto() == null ? 0 : this.getIdProyecto().hashCode() );
         return result;
   }   


}


