package titulo;
// Generated Apr 10, 2016 11:22:09 PM by Hibernate Tools 4.3.1



/**
 * SolicitarProyecto generated by hbm2java
 */
public class SolicitarProyecto  implements java.io.Serializable {


     private SolicitarProyectoId id;
     private Estudiante estudiante;
     private Proyecto proyecto;
     private String justificacion;
     private String fechaSolicitud;

    public SolicitarProyecto() {
    }

	
    public SolicitarProyecto(SolicitarProyectoId id, Estudiante estudiante, Proyecto proyecto) {
        this.id = id;
        this.estudiante = estudiante;
        this.proyecto = proyecto;
    }
    public SolicitarProyecto(SolicitarProyectoId id, Estudiante estudiante, Proyecto proyecto, String justificacion, String fechaSolicitud) {
       this.id = id;
       this.estudiante = estudiante;
       this.proyecto = proyecto;
       this.justificacion = justificacion;
       this.fechaSolicitud = fechaSolicitud;
    }
   
    public SolicitarProyectoId getId() {
        return this.id;
    }
    
    public void setId(SolicitarProyectoId id) {
        this.id = id;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public String getJustificacion() {
        return this.justificacion;
    }
    
    public void setJustificacion(String justificacion) {
        this.justificacion = justificacion;
    }
    public String getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(String fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }




}


